name: ingests-dev
channels:
  - conda-forge
dependencies:
  - python<3.12
  - numpy
  - scipy
  - xarray
  - matplotlib
  - netcdf4
  - pillow
  - metpy
  - numpy
  - pip
  - pip:
    - sage-data-client
    - ambient-api
